### ISSUE TITLE
Mass Order Cancellation

### ISSUE THREAD

**Issue by jarry-xiao** [Bonfida/agnostic-orderbook#17]
It would be a good idea to support an instruction that allows a user to cancel all of the orders that belong to them. You can do so by iterating through all of the leaves of the orderbook and matching against some identifier bytes in the corresponding `callback_info`.

This is useful for clearing out the book for market makers who need to pull their quotes, and it's also useful for closing markets (in the case of expiration for example).

I think the instruction needs to take in 2 params:

```
struct Params {
    pub num_orders: u64,
    pub callback_id: Vec<u8>
}
```

As long as the market authority signs this transaction, any upstream program should be able to handle the authorization logic for when this instruction can be invoked.

Let me know your thoughts here, I would be happy to personally implement it if you think this is a reasonable feature

**Comment by jarry-xiao** [comment]
Might be reasonable to pass in a side ordering as well (a MM might want to cancel their top N most aggressive offers as opposed to bids depending on current market dynamics)

**Comment by jarry-xiao** [comment]
Additionally all of the cancelled orders can be emitted as Out events on the event queue.

**Comment by BunnyNomics101** [comment]
Yeah it would be a nice feature for the MM. I wonder how it would affect market dynamics though. We are building on a fork and would very much have your input: BunnyNomics101@gmail.com

**Comment by jarry-xiao** [comment]
I don't think any upstream contract should natively support this (seems like a cheat code for every MM to call `mass_cancel`), but it probably makes sense if you're implementing a liquidation/orderbook cleanup or you wanted to have some type of protection logic for a MM getting overfilled.

**Comment by BunnyNomics101** [comment]
Ah yes, I understand what you mean. Following your recent video the dex-v's openorders account is decoupled from ask/bid + event queue on aob so I was thinking more of max limit and time expiration for the MM. For example, max 5 orders with expiration after certain epoch or something.

Btw, is there any way to contact you out of git? We have a few technical questions. I guess we can take it here as well.

**Comment by ellttBen** [comment]
This feature might be integrated into the AOB's next version, depending on how feasible it proves to be.

**Comment by ellttBen** [comment]
Closing this since this was implemented a while ago.
