### ISSUE TITLE
Compute budget inefficiencies

### ISSUE THREAD

**Issue by jarry-xiao** [Bonfida/agnostic-orderbook#22]
One issue that I've learned while attempting to get a sense of the compute limitations of the AOB is that every call to `buffer.borrow()` takes 20 compute units. This is not a lot in isolation, but it can definitely add up when interacting with multiple different nodes in the tree at once (like in `new_order` and in my PR for `mass_cancel_quotes`). One potential solution here could be to make it so that `get_node` takes in the `Ref` to the buffer directly as to not have make the additional borrow (gets expensive in a loop).

Another issue I noticed was that parsing a `NodeTag` was taking >40 units which I found surprising.

Something like this could improve the efficiency a bit, but it might not be the cleanest solution.
```
impl From<u8> for NodeTag {
    fn from(tag: u8) -> Self {
        match tag {
            0 => Self::Uninitialized,
            1 => Self::Inner,
            2 => Self::Leaf,
            3 => Self::Free,
            4 => Self::LastFree,
            _ => Self::Uninitialized,
        }
    }
}
```

The critical paths for both `insert` and especially `remove` should probably be as optimized to the best of our ability. I think the most straightforward win here is to just reduce borrows as much as possible. I don't know if there's any difference from a compute unit perspective between `borrow` and `borrow_mut`, but if not I would be in favor of always calling `borrow_mut` and passing around that mutable reference to both traverse and mutate the tree.

20 for the initial borrow + an additional ~20 for each memory access could probably bring each order cancellation to low something in the low 100's (assuming we have ~200 orders in the book). I'm by no means a Rust expert, but I think there could be some solid wins here.

**Comment by ellttBen** [comment]
I definitely agree with the fact that the AOB's critical path should be as optimal as possible. To be honest we're satisfied with the current performance and prefer to keep critical parts of the program unchanged for now in order to focus on adoption and developer experience.
Having said that, there are many optimisations to be made here, and I'll definitely get to reimplementing the program's data structures in order to make the AOB more efficient and more legible as well.
