### ISSUE TITLE
Feature request: Function for calculating how much of an order was filled

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#24]
Just been going through the serum v4 code. 

In projects that build on top of serum / aob, it's fairly common to want to know how much of an order was matched after a new order is placed. AOB provides an [`order summary`](https://github.com/Bonfida/agnostic-orderbook/blob/main/program/src/orderbook.rs#L18-L27) struct but the logic that's done in serum v4 is perhaps a bit complicated / confusing. Maybe some additional documentation on what the different variables e.g. `total_base_qty` vs. `total_base_qty_posted` represent under different scenarios could be helpful.

[Logic for bids](https://github.com/Bonfida/dex-v4/blob/main/program/src/processor/new_order.rs#L310-L318)
[Logic for asks](https://github.com/Bonfida/dex-v4/blob/main/program/src/processor/new_order.rs#L330-L337)

Ideally there would be a function on the `order summary` struct that could be given the details of the order that was made and return the base / quote amount that was filled (if any).

**Comment by jarry-xiao** [comment]
You can do this, but it is not at all intuitive.
`(total_base_qty - total_base_qty_posted)` is the matched base amount

Quote is nasty.
`matched_quote_amount = total_quote_qty - fp32_mul(total_base_qty, limit_price)`
where `limit_price` is from the parameters

**Comment by Henry-E** [comment]
Ah ok, that is pretty counter intuitive. Thanks for helping to clear it up. I can see where they're doing that now in the bids and asks logic.

This part was confusing at first too but I can see what's happening is that if there isn't enough quote currency free then the remainder gets transferred out of the user's account.
https://github.com/Bonfida/dex-v4/blob/main/program/src/processor/new_order.rs#L316-L322

**Comment by Henry-E** [comment]
So it seems like `total_base_qty` is the amount of quantity filled after an order has been matched and/or posted to the order book.

**Comment by Henry-E** [comment]
Just coming back to this again and still finding the order summary variables very unintuitive.
