### ISSUE TITLE
Possible bug: Code doesn't assign value to `callback_bump_index`

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#27]
Just reading through some of the code and wondering if this is a bug or an intended part of the implementation.

When updating the `SlabHeader` with data for the bids account, only the `callback_memory_offset` is updated. However, it looks like maybe the `callback_bump_index` should also be updated with the new value.

https://github.com/Bonfida/agnostic-orderbook/blob/71242678400eb942af555d19affa4c2d8554c805/program/src/critbit.rs#L236-L248

https://github.com/Bonfida/agnostic-orderbook/blob/71242678400eb942af555d19affa4c2d8554c805/program/src/critbit.rs#L258-L262

Again, not sure if this is intentional or a bug but if it is a bug then this could cause issues in the scenario that the bid and ask queues have different account sizes, i.e. the bid queue is 1mb and the ask queue is 2mb or something like that.

**Comment by ellttBen** [comment]
Hi, indeed that's not intended, I guess we didn't test out what happens when the bids and asks accounts are of different sizes. It's a quick fix though, thanks for the report!

**Comment by Henry-E** [comment]
Great, thanks for clarifying.
