### ISSUE TITLE
Feature request: Add an orderbook iterator

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#30]
Would be useful to have a built in function to iterate over leaf nodes in the orderbook / bid or ask queues.

Mango already has something like this in the form of a `BookSideIter`

https://github.com/blockworks-foundation/mango-v3/blob/main/program/src/matching.rs#L356-L369

`BookSide` is their version of `Slab`. If there's demand for this / tentative acceptance about its need from Bonfida, I could maybe make a PR for a `SlabIter`.

**Comment by dr497** [comment]
That would be a great feature to have, would you be able to make a PR for it?

**Comment by Henry-E** [comment]
Great, give me about a week or so and I might have it done. I'll add a placeholder PR for now. If it looks good, I might also apply for a small grant from the serum DAO?

**Comment by dr497** [comment]
Sure, would be happy to support a vote for this

**Comment by Henry-E** [comment]
Sounds good

**Comment by ellttBen** [comment]
Closed by PR #36

**Comment by Henry-E** [comment]
@ellttBen thanks for the PR, looks great. One feature that is missing from the mango implementation that I was considering adding was to allow the iterator to start at a node other than the root node. So for example if you have a really large orderbook or if you're making changes that have a high compute cost, then you might not be able to complete the iteration in a single transaction. The solution for this is to keep track of the current key you're at and the start the iterator again at that same key in the next transaction. 

Rust is annoying that it doesn't allow optional arguments with default parameters, since I think the solution would be to have a parameter for passing in the key to start the iterator at with the root node as the default.
