### ISSUE TITLE
Feature request: Add an option to allow order to be posted even if they cross the orderbook

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#38]
Maybe this is too niche a functionality to add but in the auction application I'm working on I want to be able to post orders to the orderbook regardless of whether it crosses the book and then run a matching algorithm at a later date.

https://github.com/Bonfida/agnostic-orderbook/blob/5ab300d78725df4e9ec76adf5ed86d2e99b6a817/program/src/orderbook.rs#L260

In my own fork, I'm going to remove `crossed` from the boolean check here because it short circuits the order if an order is `post_only == true && crossed == true`. I'm not sure what it would look like to add an option for this functionality that wouldn't mess with the existing set of options. But just putting it out there as a possibility since there is some use case for it.

**Comment by dr497** [comment]
Interesting feature but it does seem too niche. I would be interested in knowing how many other projects would use/benefit from it before adding feature like this.

**Comment by Henry-E** [comment]
For sure, that sounds reasonable.
