### ISSUE TITLE
Question: What does it mean in practice that `max_quote_qty` is fp32 but stored as u64?

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#39]
Just wondering what it means in practice that `max_quote_qty` is fp32 but stored as u64? What does it mean for client side operations? Usually quantities are stored in u64 and the number of decimals is stored somewhere else. Is there some change required to the u64 + the number of decimals before passing this into the function?

**Comment by dr497** [comment]
It means that the price you need to pass is `uiPrice * Math.pow(2, 32)`. 

Example: https://github.com/Bonfida/dex-v4/blob/main/js/src/bindings.ts#L148

**Comment by Henry-E** [comment]
Oh, does this mean the limit price is also fp32?

**Comment by dr497** [comment]
My bad, my initial answer was not clear at all. What I meant is that anytime you see something is `FP32` it means that it's multiplied by `2 ^ 32` and `limit_price` is one example of it.

**Comment by Henry-E** [comment]
No, you're all good, this my confusion. I misread the code comment that said limit price was fp32 and thought it was referring to the `max_quote_qty`. Just because i'd been seeing a lot of fp32 divs around the place. But now i totally understand that it's just price that is fp32. Thanks!

**Comment by Henry-E** [comment]
It might be worth having some documentation (maybe you do already) around the decisions made regarding handling decimals in SPL tokens. This extends to all the choices you guys made around how to treat quote and base quantities. Like for example, there's probably no issues if quote and base tokens have different mint decimal values but it would be good for people to be able to read up on this and understand it fully.

**Comment by dr497** [comment]
I agree, it's not clear enough. We will add it to the `README` and cargo doc as well

**Comment by dr497** [comment]
https://github.com/Bonfida/agnostic-orderbook/pull/41#issue-1183317581
