### ISSUE TITLE
Question: How do i use this program to build a simple Swap program?

### ISSUE THREAD

**Issue by harsh4786** [Bonfida/agnostic-orderbook#40]
I wanted to make a program that cpi's this one to make a simple swap

**Comment by harsh4786** [comment]
Also where do i contact y'all to ask noob questions like this one?

**Comment by dr497** [comment]
Here is an example of a DEX built on top of the AOB https://github.com/Bonfida/dex-v4

For these types of questions https://forum.bonfida.org/ is more adapted than Github issues.
