### ISSUE TITLE
Issue with loading slab iterator

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#44]
Just having some trouble with loading the slab iterator

```rust
        let mut orderbook = OrderBookState::new_safe(
            &ctx.accounts.bid_queue.to_account_info(),
            &ctx.accounts.ask_queue.to_account_info(),
            CALLBACK_INFO_LEN,
            CALLBACK_ID_LEN,
        )?;

        let bid_slab = orderbook.get_tree(Side::Bid);
        let bid_iter = bid_slab.into_iter(false);
```

This gives a compile error
```
cannot move out of `*bid_slab` which is behind a mutable reference
move occurs because `*bid_slab` has type `Slab<'_>`, which does not implement the `Copy` traitrustc[E0507](https://doc.rust-lang.org/error-index.html#E0507)
```

Is it possible that I'm using the wrong way to load the slab iterator?

**Comment by ellttBen** [comment]
Hi @Henry-E,
This is something we'll have to fix by implementing the `iter()` method on `Slab` which would take a reference to `self` in addition to `into_iter`. In the meantime my advice would be to just call `clone` on the slab object before doing `into_iter`. The slab object itself only contains a reference to the underlying data, which means that cloning it can be done at little to no cost.

**Comment by ellttBen** [comment]
We might also just make `Slab` a `Copy` struct.

**Comment by Henry-E** [comment]
Ah good idea, I added `clone` and it compiles correctly now. Thanks!
