### ISSUE TITLE
Order book panics when out of space, instead of removing order

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#50]
I've been trying out different byte sizes for the bid and asks queue, but for some byte sizes it will panic before it runs out of space for orders.
```
`Program log: panicked at 'called `Result::unwrap()` on an `Err` value: Kind(UnexpectedEof)', /root/projects/agnostic-orderbook/program/src/orderbook.rs:281:14`
```
which corresponds to this line 
https://github.com/Bonfida/agnostic-orderbook/blob/87493c0e347ed6feccf1b17085a377d07a922437/program/src/orderbook.rs#L270-L273

My fork is up-to-date with the latest version https://github.com/Bonfida/agnostic-orderbook/compare/main...Henry-E:main

**Comment by Henry-E** [comment]
So i did more tests and found this was linked to the call back bytes.

It looks like there's a dead zone when assigning number of bytes. Here's the calculation you need to follow to replicate this error.
`slabheader_len = 104 bytes`
`slot_size = 40 * 2 = 80`
`callback_len = variable depending on task`
`max_num_orders = variable depending on desire`

(104 + (80 + callback_len) * max_num_orders) - 1 < space / bytes assigned to account < (104 + (80 + callback_len) * max_num_orders) + callback_len

Anything between these two values will cause the above error. The key here seems to be that's linked to the callback_len. Having excess bytes / space on the account is fine, so long as the number of redundant bytes is greater than the callback_len.

So my best guess is that the calculation for the `bid/ask_order_capacity` might need to be updated to eliminate this dead zone. Though I'm not totally sure.

**Comment by Lcchy** [comment]
Hi, thanks for the issue,
I think we can ask the slab account size to be more compliant by checking that `asks/bids_account.data_len() % (SLOT_SIZE * 2 + callback_info_len) == 0` in the create market instruction and returning an error otherwise.
If you agree I'll open a PR so that we can merge it soon.

**Comment by Henry-E** [comment]
That equation looks quite different from what's currently in the space checks? I think you can just make sure to round down when dividing by the correct amount of space needed for a single order rather than erroring if a perfect space isn't given. That's what the current function does, it's just that it has the maths wrong somehow.

**Comment by Lcchy** [comment]
I just opened this PR that aims at fixing the underlying issue, let me know if this works for you

**Comment by Henry-E** [comment]
I didn't test extensively but it does seem to fix the issue. I tried out some of the byte sizes for accounts that were breaking before and everything seems to be removed from the order book correctly.

**Comment by Lcchy** [comment]
Nice thanks, I'll close this
