### ISSUE TITLE
More FP maths errors

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#60]
Following the previous advice I switched to using u64::max as the `max_quote_qty` in `new_order::params`.

However now there's some actual bad maths occurring. Not money losing but definitely incorrect and frustrating.

```
    Program log: params: Params { max_base_qty: 100000000000000, max_quote_qty: 18446744073709551615, limit_price: 858993400, side: Ask, match_limit: 1, callback_info: [41, 86, 95, 46, 36, 249, 213, 204, 152, 102, 187, 132, 192, 124, 21, 22, 110, 98, 167, 177, 185, 5, 92, 244, 250, 77, 243, 219, 45, 249, 158, 178], post_only: true, post_allowed: true, self_trade_behavior: AbortTransaction }
    Program log: u64::max as fp32: 79228162514264337589248983040
    Program log: limit price in fp32: 858993400
    Program log: divided values, before going back to u64: 92233726725099794235
    Program log: base_qty_to_post: 6356552036155
    Program log: order summary OrderSummary { posted_order_id: Some(15845631410805618355103334400), total_base_qty: 6356552036155, total_quote_qty: 1271310319614, total_base_qty_posted: 6356552036155 }
    Program log: max base qty 100000000000000
```

The problem is stemming from these lines https://github.com/Bonfida/agnostic-orderbook/blob/e37a30793f58029f1a89e1efbb7a5ea2533bf376/program/src/orderbook.rs#L257-L260

In plain language
- a post order to sell 100 million tokens (6 decimal places) is being made
- the asking price is 0.2
- the posted order is for only 6 million tokens
  - this is because `fp32_div(u64::MAX / (0.2 as FP32 % 0.001 (the tick size))) = 6.35 million` which is lower than 100 million tokens, hence it's chosen as the `base_qty_to_post` 

What am I doing wrong here?

(and yes this is using the checked maths of bonfida utils, not the old unchecked FP32 utils functions which were quietly deleted)

**Comment by Henry-E** [comment]
Maybe this is a loss of funds thing 🤷 ? The fact it returns the value of 6 million could be because of an overflow when casting down from u128 to u64. This was mentioned in the neodyme article https://blog.neodyme.io/posts/solana_common_pitfalls#integer-overflow-%26-underflow . Instead of casting `as` you should always try to use `try_from`.

**Comment by dr497** [comment]
I originally did not put checked_math in the fp32 utils for divisions because I was assuming `b_fp32 > 1 << 32` but in this case that would lead to an overflow. I added the checks https://github.com/Bonfida/bonfida-utils/pull/13

In your case the overflow was happening because `b_fp32. < 1 << 32` and you were using `u64::MAX`. You can just use `u64::MAX / 10` and it should work fine.

**Comment by Henry-E** [comment]
```
I was assuming `b_fp32 > 1 << 32`
```

Sorry but isn't the point of using fixed point to have decimals?
