### ISSUE TITLE
Event queue bricked if byte size is not correct

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#62]
Similar to the order book size issue, if the event queue space does not exactly equal (33 + 42 + event_size * num_events) bytes, then the event queue is bricked.

The way this happens is
- the event queue fills up with events
- consume events is called multiple times
- the `head` variable of the event queue header gets moved close to the end of buffer
- The next event to be added to the event queue causes the error 
```
Program log: panicked at 'range end index 1000067 out of range for slice of length 1000000', /root/projects/agnostic-orderbook/program/src/state.rs:381:18
```
  which at my best guess is linked to these lines here.
  https://github.com/Bonfida/agnostic-orderbook/blob/65d4cb06158edf15100a8de21446b42e3876d225/program/src/state.rs#L403-L405
or here
https://github.com/Bonfida/agnostic-orderbook/blob/65d4cb06158edf15100a8de21446b42e3876d225/program/src/state.rs#L361-L377
Though I don't know exactly what the maths fix should be.

**Comment by ellttBen** [comment]
This has been fixed by implementing proper allocation size checks
