### ISSUE TITLE
crates.io status

### ISSUE THREAD

**Issue by matteosantama** [Bonfida/agnostic-orderbook#65]
I see that `agnostic_orderbook` has been yanked from crates.io. To add it as a dependency is it recommended to use a git url?

**Comment by 0xBraunGuy** [comment]
+1, would love to get it back into the repo. i also think it would be good to push out crates in sync with the NPM packages, I've had discrepancies between the front end and back end versions of the code.

**Comment by kevinheavey** [comment]
Not having this on crates.io means anything that uses the AOB can't be published on crates.io either
