### ISSUE TITLE
Better documentation / examples for fp32?

### ISSUE THREAD

**Issue by 0xBraunGuy** [Bonfida/agnostic-orderbook#66]
The README mentions the specifics of the fp32 functionality, but there are no examples or tests that showcase proper usage, specifically when calling from a TS client or UI.  I'm trying to do basic testing with 8 or 12 decimal places and immediately losing precision.  From what I understand:

- All decimals/floats must be converted to an integer (bn.js) before submitting to the contract (all prices, quantities, sizes)
- Only tickSize & limitPrice are supposed to be converted to fp32 before submitting to the contract

So for example, how do I not immediately lose precision if I need 8 decimal places across the board but I also want to submit a new order at a price of 10 or 20 (whole numbers)?

The [tests](https://github.com/Bonfida/agnostic-orderbook/blob/main/js/src/tests/end_to_end.test.ts) use only whole numbers and there are no bitshifts or conversions.

**Comment by 0xBraunGuy** [comment]
Another example I'm confused about.  The u64 max is `18446744073709551615` , so if we convert this from a FP32, it's `4294967295`.  So for example if we needed to use 8 decimal places here, the maximum value would be about `42.94`.  

Trying to convert a price of `42.95` results in a `bn.js` error due to the u64 overflow `Error: byte array longer than desired length`

Unless I'm missing something?

**Comment by ellttBen** [comment]
Hey @0xBraunGuy, so in your examples the 8 decimals would be an 8 decimal _difference_ between your quote and base tokens. For instance, if both your tokens have the same amount of decimals, the maximum price becomes 4294967295.99..

The way things are designed right now, the caller program is responsible for dealing with potential issues that can arise from a big decimal difference, or just from this maximum being too low. For an example of how to deal with this, you can check out this draft dex-v4 PR : https://github.com/Bonfida/dex-v4/pull/70

**Comment by ellttBen** [comment]
Regarding the documentation itself, this is definitely something we're working on improving. In the meantime, my best advice would be to get familiar with the Bonfida/dex-v4 repo, because it represents a _relatively_ simple use of the AOB, while making use of all its features.

**Comment by 0xBraunGuy** [comment]
Understood, thanks @ellttBen .
