### ISSUE TITLE
Incorrect market account space gives weird error

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#73]
The correct amount of bytes is
- the size of the market struct: 112
- the discriminator: 8
= 120 bytes

But if you pass the wrong number of bytes it gives an incomprehensible error.
    `Program log: panicked at 'from_bytes_mut>SizeMismatch', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.10.0/src/internal.rs:30:3`

**Comment by ellttBen** [comment]
Solved by PR #86.
