### ISSUE TITLE
Error in Initial Build

### ISSUE THREAD

**Issue by brendan-mccaffrey** [Bonfida/agnostic-orderbook#90]
I'm looking to build on top of Bonfida's repos (Dex_v4 + agnostic orderbook). I have errors in the code immediately after cloning, specifically type conflict errors shown here.

Reproduce: Clone repo, navigate to /program/ and run cargo doc --open
![Screen Shot 2022-10-24 at 2 02 11 PM](https://user-images.githubusercontent.com/51927517/197594478-267040a0-46df-42e4-a16d-84eb011f5936.png)

**Comment by dr497** [comment]
Similar to https://github.com/Bonfida/agnostic-orderbook/issues/43
