### ISSUE TITLE
Nitpick: returning a solana program error instead of a custom error

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#91]
Maybe this is just a style / preference thing but whenever an incorrect tag on the account is detected AOB returns a solana program `InvalidAccountData` error. All things considered, it seems pretty reasonable to have a more verbose custom error that just says `account tags didn't match` or something like that.

 https://github.com/Bonfida/agnostic-orderbook/blob/36914065e2eb3e289a4f87ee6e3b36be51db58cf/program/src/state/market_state.rs#L39

**Comment by ellttBen** [comment]
Closing this with PR #92. Thanks for the suggestion!
