### ISSUE TITLE
Error: ELF error: ELF error: Multiple or no text sections, consider removing llc option: -function-sections

### ISSUE THREAD

**Issue by michaelzigzag** [Bonfida/agnostic-orderbook#97]
while deploy program with "solana program deploy ./target/deploy/agnostic_orderbook.so "  i get 
"Error: ELF error: ELF error: Multiple or no text sections, consider removing llc option: -function-sections"

**Comment by michaelzigzag** [comment]
i build with cargo build-sbf

**Comment by SPACE999978** [comment]
did you ever solve this?

**Comment by DavidSparker0417** [comment]
I've the same problem.
I would appreciate someone help me way out.

**Comment by mabdelmenam** [comment]
Did anyone find a solution?

**Comment by ellieasager** [comment]
The same issue 😢 Can't even deploy Hello World
Does anybody read this?

**Comment by ellttBen** [comment]
Also taking a look at this, sorry for the delay. I think I just need to freshen up a few things here. Also worth a note here, the AAOB is not supposed to be compiled directly, it's supposed to be used as a library within another program. You can find an example of this usage here: https://github.com/bonfida/dex-v4

**Comment by ellttBen** [comment]
I have dusted off the packages, current changes can be found in the `renamed_for_publish` branch, if people want to try it out.

**Comment by ellttBen** [comment]
The new release should fix most issues. If you really want to compile the AAOB directly as a program, you should use the entrypoint feature (`cargo build-sbf --features entrypoint`). Usually crates have a `no-entrypoint` feature instead of an `entrypoint` feature, but as stated previously the AAOB is supposed to be use as a library.
